<?php

/**
 * @file
 * Markdown module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\markdown\Markdown;

/**
 * Implements hook_help().
 *
 * {@inheritdoc}
 */
function markdown_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.markdown':
      return Markdown::create()->loadPath(__DIR__ . '/README.md');
  }
}

/**
 * Implements hook_modules_installed().
 *
 * {@inheritdoc}
 */
function markdown_modules_installed($modules) {
  // Immediately return if not installing the markdown module.
  if (!in_array('markdown', $modules, TRUE)) {
    return;
  }

  // Save the first found parser as the default global parser.
  /** @var \Drupal\markdown\MarkdownParserPluginManagerInterface $parserManager */
  $parserManager = \Drupal::service('plugin.manager.markdown.parser');
  if ($parser = current(array_keys($parserManager->installedDefinitions()))) {
    \Drupal::configFactory()->getEditable('markdown.settings')->set('parser.id', $parser)->save();
  }
}
